export let crapsRules = [
  "Playing craps in Vegas is an exciting, fast-paced, action-packed game utilizing a pair of dice. Are you wondering how to play craps at a game? Here are some basics to get you started at a Vegas craps table or craps slot machines.",
  "One player, known as the “shooter,” throws the dice. All wagers must be placed before the shooter throws the dice. The types of wagers that can be made are:",
  "",
  "PLACE BETS:",
  "Once a shooter makes a point, you may make a “place bet” on numbers 4, 5, 6, 8, 9, and 10. If the shooter rolls any of these numbers before a 7, you win the following payoffs: 9 to 5 on 4 and 10, 7 to 5 on 5 and 9, and 7 to 6 on 6 and 8.",
  "",
  "A “place bet” may be taken off anytime before the next roll.",
  "",
  "FIELD BETS:",
  "A one roll bet. You win even money on 3, 4, 9, 10 and 11. You win 2 to 1 on 2. You win 3 to 1 on 12. You lose on 5, 6, 7 or 8.",
  "",
  "PROPOSITION BETS:",
  "These bets are found in the center of the table and are one-roll bets. You are betting that on the very next roll of the dice any of these numbers will come up:",
  "",
  "Any Craps (2, 3 or 12)	pays 8 for 1",
  "Aces (2) or Twelve (12)	pays 31 for 1",
  "Ace-Deuce (3) or Eleven (11)	pays 16 for 1",
  "Seven (7)	pays 5 for 1",
  "",
  "HARDWAYS:",
  "A Hardway bet is not a one-roll bet. You are betting that the shooter rolls a pair. Hardways win if the dice roll as a pair and lose if a 7 rolls or if the number is thrown “the easy way.” Example: If you bet a hard 8 and thedice roll 4,4 you win. If the dice roll “easy” 5,3 or 6,2 you lose.",
  "",
  "Hard Four or Ten	pays 8 for 1",
  "Hard Six or Eight	pays 10 for 1",
  "",
  "HOP BETS:",
  "Hop Bets are a one roll bet on a specific combination of the dice. You are literally betting on what you think the very next roll of the dice will be.",
  "",
  "If you think the next roll is going to be a (6, 3), you would tell the dealer that you want the 6 and 3 hopping. Hop bets pay 31 for 1 or 16 for 1 depending on the combination that you choose.",
];
