export let pokerRules = [
    "Poker is played from a standard pack of 52 cards. (Some variant games use multiple packs or add a few cards called jokers.) The cards are ranked (from high to low) Ace, King, Queen, Jack, 10, 9, 8, 7, 6, 5, 4, 3, 2, Ace. (Ace can be high or low, but is usually high). There are four suits (spades, hearts, diamonds and clubs); however, no suit is higher than another. All poker hands contain five cards, the highest hand wins.",
  "Hands are ranked as follows (from high to low) + Betting:",
  "Royal Flush - 100,000:1",
  "Straight Flush - 10,000:1",
  "Four of a Kind - 1,000:1",
  "Full House - 100:1",
  "Flush - 50:1",
  "Straight - 25:1",
  "Three of a Kind - 10:1",
  "Two Pair - 5:1",
  "Pair - 1:1",
  "",
  "Select a chip you want to bet (Single Betting) after you receive your cards.",
  "",
  "Holding:",
  "Once cards are dealt to you, you have the option to hold a card. Holding is where you keep a card in your hand when a new deal is ordered. Holding gives a higher chance of getting a higher bet.",
  "",
];